### ISSUE TITLE
Describe what future is

### ISSUE THREAD

**Issue by abuseofnotation** [stoeffel/redux-future#2]
I think that it will be useful to describe what a Future is or link to a doc where it is described.

**Comment by stoeffel** [comment]
Will do. It's on my todo list. I will probably just link to this great post. http://robotlolita.me/2014/03/20/a-monad-in-practicality-controlling-time.html

**Comment by stoeffel** [comment]
added some resources and links to libraries. What do you think? Enough?

**Comment by abuseofnotation** [comment]
Yes

**Comment by stoeffel** [comment]
Cool. Let me know if you have other feedback.
