### ISSUE TITLE
Doesn't set status on success

### ISSUE THREAD

**Issue by rjmk** [stoeffel/redux-future#4]
Hey! Cool module. In the readme you write

> If it receives an Flux Standard Action whose payload is a future, it will fork and then either
> - dispatch a copy of the action with the resolved value of the future, and set status to success.
> - dispatch a copy of the action with the rejected value of the future, and set status to error.

I think that would be cool! [Currently an error field is set to true in a rejected case and no flag is set in the success case](https://github.com/stoeffel/redux-future/blob/b05d7e89fcd378efeaa2b4b24e9e2b54b56f7669/src/index.js#L22-L23)

**Comment by stoeffel** [comment]
> Hey! Cool module

Thanks :smile: 

[Flux-Standart-Action](https://github.com/acdlite/flux-standard-action) doesn't have a success flag. I will remove that comment to make it comply with that. I don't see a need for a success flag when you can check for a presence of an error.
